from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageholder = QtWidgets.QListWidget(self.centralwidget)
        self.imageholder.setGeometry(QtCore.QRect(0, 150, 671, 471))
        self.imageholder.setObjectName("imageholder")
        self.Selectimg = QtWidgets.QPushButton(self.centralwidget)
        self.Selectimg.setGeometry(QtCore.QRect(0, 620, 221, 41))
        self.Selectimg.setObjectName("Selectimg")
        self.Filename = QtWidgets.QLineEdit(self.centralwidget)
        self.Filename.setGeometry(QtCore.QRect(220, 620, 451, 41))
        self.Filename.setObjectName("Filename")
        self.possiblePlateholder = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlateholder.setGeometry(QtCore.QRect(810, 250, 271, 521))
        self.possiblePlateholder.setObjectName("possiblePlateholder")
        self.title = QtWidgets.QTextEdit(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 20, 751, 61))
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setObjectName("title")
        self.possiblePlates1 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates1.setGeometry(QtCore.QRect(840, 270, 221, 41))
        self.possiblePlates1.setObjectName("possiblePlates1")
        self.possiblePlates2 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates2.setGeometry(QtCore.QRect(840, 310, 221, 41))
        self.possiblePlates2.setObjectName("possiblePlates2")
        self.possiblePlates3 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates3.setGeometry(QtCore.QRect(840, 350, 221, 41))
        self.possiblePlates3.setObjectName("possiblePlates3")
        self.possiblePlates4 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates4.setGeometry(QtCore.QRect(840, 390, 221, 41))
        self.possiblePlates4.setObjectName("possiblePlates4")
        self.possiblePlates5 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates5.setGeometry(QtCore.QRect(840, 430, 221, 41))
        self.possiblePlates5.setObjectName("possiblePlates5")
        self.possiblePlates10 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates10.setGeometry(QtCore.QRect(840, 630, 221, 41))
        self.possiblePlates10.setObjectName("possiblePlates10")
        self.possiblePlates8 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates8.setGeometry(QtCore.QRect(840, 550, 221, 41))
        self.possiblePlates8.setObjectName("possiblePlates8")
        self.possiblePlates11 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates11.setGeometry(QtCore.QRect(840, 670, 221, 41))
        self.possiblePlates11.setObjectName("possiblePlates11")
        self.possiblePlates12 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates12.setGeometry(QtCore.QRect(840, 710, 221, 41))
        self.possiblePlates12.setObjectName("possiblePlates12")
        self.possiblePlates9 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates9.setGeometry(QtCore.QRect(840, 590, 221, 41))
        self.possiblePlates9.setObjectName("possiblePlates9")
        self.possiblePlates6 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates6.setGeometry(QtCore.QRect(840, 470, 221, 41))
        self.possiblePlates6.setObjectName("possiblePlates6")
        self.possiblePlates7 = QtWidgets.QListWidget(self.centralwidget)
        self.possiblePlates7.setGeometry(QtCore.QRect(840, 510, 221, 41))
        self.possiblePlates7.setObjectName("possiblePlates7")
        self.filetype = QtWidgets.QListWidget(self.centralwidget)
        self.filetype.setGeometry(QtCore.QRect(570, 620, 101, 41))
        self.filetype.setObjectName("filetype")
        self.PossiblePlates = QtWidgets.QTextEdit(self.centralwidget)
        self.PossiblePlates.setGeometry(QtCore.QRect(820, 200, 251, 51))
        self.PossiblePlates.setObjectName("PossiblePlates")
        self.possiblePlateholder.raise_()
        self.imageholder.raise_()
        self.Selectimg.raise_()
        self.Filename.raise_()
        self.title.raise_()
        self.possiblePlates1.raise_()
        self.possiblePlates2.raise_()
        self.possiblePlates3.raise_()
        self.possiblePlates4.raise_()
        self.possiblePlates5.raise_()
        self.possiblePlates10.raise_()
        self.possiblePlates8.raise_()
        self.possiblePlates11.raise_()
        self.possiblePlates12.raise_()
        self.possiblePlates9.raise_()
        self.possiblePlates6.raise_()
        self.possiblePlates7.raise_()
        self.filetype.raise_()
        self.PossiblePlates.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Selectimg.setText(_translate("MainWindow", "Select Image"))
        self.title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt;\">Automated Number Plate Recognition</span></p></body></html>"))
        self.PossiblePlates.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Possible number plates</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
